version: '3.5'
services:
  proxy:
    #restart: unless-stopped
    build:
      context: .
    environment:
      - CAMERA_CAM1_HOST=user:pass@192.168.1.50
      - CAMERA_CAM1_ENABLED_JPG=false
      - CAMERA_CAM2_HOST=user:pass@192.168.1.60
      - CAMERA_CAM2_ENABLED_RTSP=false
    ports:
      - 8080:80
    # sysctls:
    #   net.ipv4.ip_unprivileged_port_start: 0
